/**
 * Calendar — month grid view with events from `/calendar-events/by-range`.
 * Click a cell to add an event; click an event chip to edit/delete.
 */

import { useEffect, useMemo, useState } from 'react';
import { toast } from 'react-toastify';
import {
  Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle,
  IconButton, MenuItem, Paper, Stack, TextField, Tooltip, Typography,
} from '@mui/material';
import {
  Add, ChevronLeft, ChevronRight, Delete, Event as EventIcon, Today,
} from '@mui/icons-material';
import calendarEventService from '../../../services/calendarEvent.service';
import { useAcademicYear } from '../../../contexts/AcademicYearContext';
import { useT } from '../../../contexts/I18nContext';
import type {
  CalendarEventRequest, CalendarEventResponse, CalendarEventType,
} from '../../../types/calendarEvent';

const EVENT_TYPES: CalendarEventType[] = [
  'WORKING_DAY', 'HOLIDAY', 'HALF_DAY', 'EXAM',
  'EVENT', 'TEACHER_MEETING', 'SPORTS_DAY', 'PARENT_TEACHER_MEETING',
];

const TYPE_COLORS: Record<CalendarEventType, string> = {
  WORKING_DAY: '#10b981',
  HOLIDAY: '#ef4444',
  HALF_DAY: '#f59e0b',
  EXAM: '#7c3aed',
  EVENT: '#2563eb',
  TEACHER_MEETING: '#06b6d4',
  SPORTS_DAY: '#84cc16',
  PARENT_TEACHER_MEETING: '#ec4899',
};

function startOfMonth(d: Date) { return new Date(d.getFullYear(), d.getMonth(), 1); }
function endOfMonth(d: Date) { return new Date(d.getFullYear(), d.getMonth() + 1, 0); }
/** Local YYYY-MM-DD — never use toISOString() here, that converts to UTC and shifts dates by ±1 day in non-UTC zones. */
function ymd(d: Date) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}
function daysInMonth(year: number, month: number) { return new Date(year, month + 1, 0).getDate(); }

export default function CalendarPage() {
  const { t } = useT();
  const { active: activeYear } = useAcademicYear();
  const [cursor, setCursor] = useState(new Date());
  const [events, setEvents] = useState<CalendarEventResponse[]>([]);
  const [loading, setLoading] = useState(false);

  const [openDialog, setOpenDialog] = useState(false);
  const [editing, setEditing] = useState<CalendarEventResponse | null>(null);
  const [draft, setDraft] = useState<CalendarEventRequest>({
    eventDate: ymd(new Date()),
    eventType: 'EVENT',
    title: '',
  });
  const [saving, setSaving] = useState(false);

  const monthStart = useMemo(() => startOfMonth(cursor), [cursor]);
  const monthEnd = useMemo(() => endOfMonth(cursor), [cursor]);

  const fetchEvents = () => {
    setLoading(true);
    calendarEventService.byRange(ymd(monthStart), ymd(monthEnd))
      .then(setEvents)
      .catch((err) => toast.error(err.message || 'Failed to load events'))
      .finally(() => setLoading(false));
  };

  useEffect(() => { fetchEvents(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [cursor]);

  const eventsByDate = useMemo(() => {
    const m = new Map<string, CalendarEventResponse[]>();
    // Backend may return YYYY-MM-DD or full ISO ('2026-05-09T00:00:00'). Slice
    // to YYYY-MM-DD so the key matches the cell key generated by ymd().
    const norm = (raw: string | undefined) => (raw || '').slice(0, 10);
    events.forEach((e) => {
      const start = norm(e.eventDate);
      const end = norm(e.endDate) || start;
      if (!start) return;
      // Multi-day events: index every day in range.
      const s = new Date(start);
      const en = new Date(end);
      for (let d = new Date(s); d <= en; d.setDate(d.getDate() + 1)) {
        const key = ymd(d);
        const list = m.get(key) || [];
        list.push(e);
        m.set(key, list);
      }
    });
    return m;
  }, [events]);

  const openCreate = (date: Date) => {
    setEditing(null);
    setDraft({
      eventDate: ymd(date),
      eventType: 'EVENT',
      title: '',
      academicYearId: activeYear?.id,
    });
    setOpenDialog(true);
  };

  const openEdit = (e: CalendarEventResponse) => {
    setEditing(e);
    setDraft({
      eventDate: e.eventDate,
      endDate: e.endDate,
      eventType: e.eventType,
      title: e.title,
      description: e.description,
      academicYearId: e.academicYearId,
      applicableSections: e.applicableSections,
      audienceType: e.audienceType,
    });
    setOpenDialog(true);
  };

  const save = async () => {
    if (!draft.title.trim()) { toast.error('Title is required'); return; }
    setSaving(true);
    try {
      if (editing) {
        await calendarEventService.update(editing.id, draft);
        toast.success('Event updated');
      } else {
        // Use the /academic endpoint on create: backend's plain /calendar-events
        // currently drops `audienceType` (returns null on persist), while
        // /calendar-events/academic correctly stores the audience flag —
        // which the search endpoint then uses to filter for PARENT/STUDENT
        // viewers. Routing every create here keeps the audience picker honest.
        await calendarEventService.createAcademic(draft);
        toast.success('Event added');
      }
      setOpenDialog(false);
      fetchEvents();
    } catch (err) {
      toast.error((err as { message?: string }).message || 'Save failed');
    } finally {
      setSaving(false);
    }
  };

  const remove = async (e: CalendarEventResponse) => {
    if (!window.confirm(`Delete "${e.title}"?`)) return;
    try {
      await calendarEventService.remove(e.id);
      toast.success('Deleted');
      fetchEvents();
      setOpenDialog(false);
    } catch (err) {
      toast.error((err as { message?: string }).message || 'Delete failed');
    }
  };

  // Render month grid
  const firstWeekday = monthStart.getDay(); // 0 = Sunday
  const totalDays = daysInMonth(cursor.getFullYear(), cursor.getMonth());
  const cells: (Date | null)[] = [];
  for (let i = 0; i < firstWeekday; i++) cells.push(null);
  for (let d = 1; d <= totalDays; d++) cells.push(new Date(cursor.getFullYear(), cursor.getMonth(), d));
  while (cells.length % 7 !== 0) cells.push(null);

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3, flexWrap: 'wrap', gap: 2 }}>
        <Box>
          <Typography variant="h5" sx={{ fontWeight: 700 }}>{t('calendar.title')}</Typography>
          <Typography variant="body2" color="text.secondary">
            {activeYear ? t('calendar.academicYear', { name: activeYear.name }) : t('calendar.noActiveYear')}
          </Typography>
        </Box>
        <Stack direction="row" spacing={1} alignItems="center">
          <Tooltip title={t('calendar.today')}>
            <IconButton onClick={() => setCursor(new Date())}><Today /></IconButton>
          </Tooltip>
          <IconButton onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() - 1, 1))}>
            <ChevronLeft />
          </IconButton>
          <Typography variant="h6" sx={{ minWidth: 180, textAlign: 'center', fontWeight: 600 }}>
            {cursor.toLocaleString(undefined, { month: 'long', year: 'numeric' })}
          </Typography>
          <IconButton onClick={() => setCursor(new Date(cursor.getFullYear(), cursor.getMonth() + 1, 1))}>
            <ChevronRight />
          </IconButton>
          <Button startIcon={<Add />} variant="contained" onClick={() => openCreate(new Date())}
            sx={{ ml: 2, background: 'linear-gradient(135deg, #2563eb, #7c3aed)' }}>
            {t('calendar.newEvent')}
          </Button>
        </Stack>
      </Box>

      <Stack direction="row" spacing={1} sx={{ mb: 2, flexWrap: 'wrap', gap: 0.5 }}>
        {EVENT_TYPES.map((t) => (
          <Chip key={t} size="small" label={t.replace(/_/g, ' ')}
            sx={{ background: TYPE_COLORS[t], color: 'white', fontSize: 11 }} />
        ))}
      </Stack>

      <Paper variant="outlined" sx={{ borderRadius: 2, overflow: 'hidden' }}>
        {loading && <Box sx={{ p: 1 }}><CircularProgress size={20} /></Box>}
        <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', background: 'rgba(37,99,235,0.04)' }}>
          {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((d) => (
            <Box key={d} sx={{ p: 1.5, textAlign: 'center', fontWeight: 600, fontSize: 13, color: 'text.secondary' }}>
              {d}
            </Box>
          ))}
        </Box>
        <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)' }}>
          {cells.map((cell, i) => {
            const today = cell && ymd(cell) === ymd(new Date());
            const dayEvents = cell ? eventsByDate.get(ymd(cell)) || [] : [];
            return (
              <Box key={i}
                onClick={() => cell && openCreate(cell)}
                sx={{
                  minHeight: 110, p: 1, borderTop: '1px solid', borderLeft: i % 7 ? '1px solid' : 'none',
                  borderColor: 'divider', cursor: cell ? 'pointer' : 'default',
                  background: today ? 'rgba(37,99,235,0.04)' : 'transparent',
                  position: 'relative', transition: 'background 150ms',
                  '&:hover': cell ? { background: 'rgba(37,99,235,0.06)' } : {},
                }}>
                {cell && (
                  <>
                    <Typography variant="caption"
                      sx={{
                        fontWeight: today ? 700 : 500,
                        color: today ? 'primary.main' : 'text.secondary',
                      }}>
                      {cell.getDate()}
                    </Typography>
                    <Stack spacing={0.5} sx={{ mt: 0.5 }}>
                      {dayEvents.slice(0, 3).map((e) => (
                        <Box key={e.id}
                          onClick={(ev) => { ev.stopPropagation(); openEdit(e); }}
                          sx={{
                            background: TYPE_COLORS[e.eventType],
                            color: 'white', borderRadius: 1, px: 0.75, py: 0.25,
                            fontSize: 11, fontWeight: 500, cursor: 'pointer',
                            whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                          }}>
                          {e.title}
                        </Box>
                      ))}
                      {dayEvents.length > 3 && (
                        <Typography variant="caption" color="text.secondary">
                          {t('calendar.moreCount', { n: dayEvents.length - 3 })}
                        </Typography>
                      )}
                    </Stack>
                  </>
                )}
              </Box>
            );
          })}
        </Box>
      </Paper>

      <Dialog open={openDialog} onClose={() => setOpenDialog(false)} maxWidth="sm" fullWidth>
        <DialogTitle>
          <Stack direction="row" alignItems="center" spacing={1}>
            <EventIcon fontSize="small" />
            {editing ? t('calendar.editEvent') : t('calendar.newEvent')}
          </Stack>
        </DialogTitle>
        <DialogContent>
          <Stack spacing={2} sx={{ mt: 1 }}>
            <TextField label={t('calendar.eventTitle')} required value={draft.title}
              onChange={(e) => setDraft({ ...draft, title: e.target.value })} />
            <Stack direction="row" spacing={2}>
              <TextField type="date" label={t('calendar.eventDate')} required InputLabelProps={{ shrink: true }}
                value={draft.eventDate} fullWidth
                onChange={(e) => setDraft({ ...draft, eventDate: e.target.value })} />
              <TextField type="date" label={t('calendar.endDate')} InputLabelProps={{ shrink: true }}
                value={draft.endDate || ''} fullWidth
                onChange={(e) => setDraft({ ...draft, endDate: e.target.value || undefined })} />
            </Stack>
            <TextField select label={t('calendar.type')} value={draft.eventType}
              onChange={(e) => setDraft({ ...draft, eventType: e.target.value as CalendarEventType })}>
              {EVENT_TYPES.map((t) => (
                <MenuItem key={t} value={t}>
                  <Box sx={{ display: 'inline-block', width: 12, height: 12, borderRadius: '50%',
                    background: TYPE_COLORS[t], mr: 1, verticalAlign: 'middle' }} />
                  {t.replace(/_/g, ' ')}
                </MenuItem>
              ))}
            </TextField>
            <TextField label={t('masterData.description')} multiline rows={2} value={draft.description || ''}
              onChange={(e) => setDraft({ ...draft, description: e.target.value })} />
            <TextField select label="Audience" value={draft.audienceType || 'ALL'}
              helperText="Who can see this event"
              onChange={(e) => setDraft({ ...draft, audienceType: e.target.value as CalendarEventRequest['audienceType'] })}>
              <MenuItem value="ALL">Everyone</MenuItem>
              <MenuItem value="STUDENTS">Students only</MenuItem>
              <MenuItem value="PARENTS">Parents only</MenuItem>
              <MenuItem value="TEACHERS">Teachers only</MenuItem>
              <MenuItem value="ADMIN">Admins only</MenuItem>
            </TextField>
          </Stack>
        </DialogContent>
        <DialogActions sx={{ justifyContent: 'space-between', px: 3 }}>
          <Box>
            {editing && (
              <Button color="error" startIcon={<Delete />} onClick={() => remove(editing)}>
                {t('common.delete')}
              </Button>
            )}
          </Box>
          <Box>
            <Button onClick={() => setOpenDialog(false)} disabled={saving}>{t('common.cancel')}</Button>
            <Button variant="contained" onClick={save} disabled={saving}>
              {saving ? t('common.saving') : t('common.save')}
            </Button>
          </Box>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
